mongo:
  db_name: ineuron
  collection_name: scania_truck
artifacts_dir: scania_truck/artifacts
logs_dir: scania_truck/logs
save_format: .sav
s3_bucket:
  scania_truck_input_files_bucket: scania-truck-io-files
  scania_truck_logs_bucket: scania-truck-logs
  scania-truck-pred_bucket: scania-truck-pred-data
model_utils:
  verbose: 3
  cv: 2
  n_jobs: -1
schema_path: scania_truck/config/schema.yaml
preprocessor_obj_file_name: scania_truck/artifacts/scania_truck_preprocessor.pkl
base_model_score: '0.9424233743912919'
train_model:
  XGBClassifier:
    booster:
    - gbtree
    - dart
    max_depth:
    - 3
    - 4
    - 6
  GradientBoostingClassifier:
    loss:
    - deviance
    n_estimators:
    - 100
    - 200
    criterion:
    - friedman_mse
    - squared_error
model_file_name: model
pred_data_csv_file: scania_pred_data.csv
