mongo:
  db_name: ineuron
  collection_name: sensor

artifacts_dir: artifacts

logs_dir: logs

save_format: .sav

s3_bucket:
  sensor_input_files_bucket: sensor-io-files
  sensor_pred_bucket: sensor-pred-data

model_utils:
  verbose: 3
  cv: 2
  n_jobs: -1

schema_path: sensor/config/schema.yaml

preprocessor_obj_file_name: sensor/artifacts/sensor_preprocessor.pkl

base_model_score: "0.6"

train_model:
  XGBClassifier:
    booster:
      - gbtree
      - dart

    max_depth:
      - 3
      - 4
      - 6

  GradientBoostingClassifier:
    loss:
      - deviance

    n_estimators:
      - 100
      - 200

    criterion:
      - friedman_mse
      - squared_error

model_file_name: model

pred_data_csv_file: sensor_pred_data.csv

predictions_file: sensor_predictions.csv
