grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      n_estimators: 200
      criterion: squared_error
    search_param_grid:
      n_estimators:
        - 100
      max_depth:
        - 3

  module_1:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    search_param_grid:
      n_estimators:
        - 100
      criterion:
        - friedman_mse
