on:
  push:
    branches:
      - main
    paths:
      - infrastructure/*

name: Apply changes to infrastructure

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Initialize Terraform modules
        id: terraform-init
        run: |
          terraform -chdir=infrastructure/ init

      - name: Apply the Terraform modules
        id: terraform-apply
        run: |
          terraform -chdir=infrastructure/ apply --auto-approve